/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      white: "white",
      black: "black",
      transparent: "transparent",
      "wodden-purple": "#1F2B21",
      gray: {
        1: "#C7C7C7",
      },
    },
    fontFamily: {
      helvetica: "helvetica",
      poppins: "'Poppins', sans-serif",
    },
    extend: {
      borderWidth: {
        "1px": "1px",
      },
      spacing: {
        "0_1vw": "0.1vw",
        "0_2vw": "0.2vw",
        "0_3vw": "0.3vw",
        "0_4vw": "0.4vw",
        "0_5vw": "0.5vw",
        "0_6vw": "0.6vw",
        "0_7vw": "0.7vw",
        "0_8vw": "0.8vw",
        "0_9vw": "0.9vw",
        "1vw": "1vw",
        "1_1vw": "1.1vw",
        "1_2vw": "1.2vw",
        "1_3vw": "1.3vw",
        "1_4vw": "1.4vw",
        "1_5vw": "1.5vw",
        "1_6vw": "1.6vw",
        "1_7vw": "1.7vw",
        "1_8vw": "1.8vw",
        "1_9vw": "1.9vw",
        "2vw": "2vw",
        "3vw": "3vw",
        "4vw": "4vw",
        "5vw": "5vw",
        "6vw": "6vw",
        "7vw": "7vw",
        "8vw": "8vw",
        "9vw": "9vw",
        "10vw": "10vw",
        "12vw": "12vw",
        "14vw": "14vw",
        "15vw": "15vw",
        "16vw": "16vw",
        "18vw": "18vw",
      },
    },
  },
  plugins: [],
};
